Migrated to swift 3.0; Added CHANGELOG.md;
theappbusiness/TABSwiftLayout pull request #5
Opened 2016-09-15 13:53 UTC by danielablg

2016-09-15 14:08 UTC, lucianomarisi requested changes
Can the code in the README file use the latest API changes?

2016-09-15 15:29 UTC, danielablg commented
@lucianomarisi fixed, good catch, thanks

2016-09-15 16:25 UTC, marius-serban commented on README.md
> +view.pin(edge: .Top, toEdge: .Top, ofView: view.superview) // default margin 0
shouldn't enum cases like `.Top` start with lower case letter

2016-09-15 16:32 UTC, danielablg commented on README.md
> +view.pin(edge: .Top, toEdge: .Top, ofView: view.superview) // default margin 0
fixed

2016-09-15 16:34 UTC, lucianomarisi approved these changes

2016-09-15 18:21 UTC, samdods commented on Sources/Constraint.swift
> +  fileprivate var _enabled = true
should this still be private?

2016-09-15 18:21 UTC, samdods commented on Sources/Constraint.swift
> +  fileprivate weak var _constraint: NSLayoutConstraint?
private?

2016-09-16 13:21 UTC, danielablg commented on Sources/Constraint.swift
> +  fileprivate weak var _constraint: NSLayoutConstraint?
fixed

2016-09-16 13:22 UTC, danielablg commented on Sources/Constraint.swift
> +  fileprivate var _enabled = true
Indeed they are being used only in the lexical scope they are declared in. Fixed

2016-09-16 13:35 UTC, merged